id: power_work_predictive
name: "Moc kotła – predykcyjny (WORK)"
description: >
  Wyznaczanie mocy kotła (power %) w trybie WORK.
  Moduł uczy się typowej mocy (baseline) jako średniej wykładniczej EMA
  na podstawie realnej mocy systemu. Próbki do uczenia zbiera dopiero,
  gdy warunki są spokojne: mały błąd i małe wahania temperatury w oknie
  (span(T)=max-min w temp_span_window_s).
  Po spełnieniu minimalnego czasu i liczby próbek moduł OD RAZU przejmuje sterowanie.
  Sterowanie jest krokowe: co min_adjust_interval_s zmienia moc o takeover_step_percent
  jeśli temperatura jest poza deadband (trim_deadband_degC).
  Dodatkowo po takeover stosuje warunek trendu temperatury (okno takeover_trend_window_s),
  żeby nie dokładać/nie odejmować mocy, gdy temperatura już zmienia się we właściwym kierunku.

groups:
  - id: basic
    label: "Podstawowe"
  - id: learning
    label: "Uczenie baseline (EMA)"
  - id: takeover
    label: "Przejęcie sterowania"
  - id: state
    label: "Stan (restart)"

fields:
  - key: enabled
    label: "Regulator aktywny"
    type: bool
    default: true
    label_on: "WŁĄCZONE"
    label_off: "WYŁĄCZONE"
    group: basic
    description: >
      Gdy wyłączone, moduł nie nadpisuje outputs.power_percent
      i nie przejmuje sterowania.

  - key: boiler_set_temp
    label: "Zadana temperatura kotła"
    type: number
    unit: "°C"
    min: 40
    max: 90
    step: 1
    default: 56
    group: basic
    description: "Temperatura, do której dąży regulator w trybie WORK."

  - key: min_power
    label: "Minimalna moc"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 15
    group: basic
    description: "Dolne ograniczenie mocy (w WORK)."

  - key: max_power
    label: "Maksymalna moc"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 100
    group: basic
    description: "Górne ograniczenie mocy (w WORK)."

  - key: min_adjust_interval_s
    label: "Min. odstęp między korektami mocy"
    type: number
    unit: "s"
    min: 0
    max: 3600
    step: 1
    default: 60
    group: takeover
    description: >
      Ogranicza częstotliwość zmian mocy po przejęciu sterowania.
      0 oznacza zmianę w każdym ticku.

  - key: takeover_step_percent
    label: "Takeover: krok zmiany mocy"
    type: number
    unit: "pkt%"
    min: 0.1
    max: 10
    step: 0.1
    default: 1.0
    group: takeover
    description: >
      O ile pkt% zmieniać moc co min_adjust_interval_s, jeśli temperatura
      jest poza deadband (i nie jest zablokowana przez warunek trendu).

  - key: trim_deadband_degC
    label: "Deadband temperatury"
    type: number
    unit: "°C"
    min: 0
    max: 5
    step: 0.1
    default: 0.5
    group: takeover
    description: >
      Jeśli |błąd| <= deadband, moc nie jest zmieniana (krok=0).

  - key: takeover_trend_window_s
    label: "Takeover: okno trendu temperatury"
    type: number
    unit: "s"
    min: 60
    max: 7200
    step: 30
    default: 600
    group: takeover
    description: >
      Okno czasowe do oceny trendu temperatury (po filtrze).
      Używane do blokowania dokładania/odejmowania mocy, gdy temperatura
      już zmienia się w oczekiwanym kierunku.

  - key: takeover_hold_rise_degC
    label: "Takeover: nie dokładaj mocy gdy T rośnie o ≥"
    type: number
    unit: "°C"
    min: 0
    max: 10
    step: 0.1
    default: 0.8
    group: takeover
    description: >
      Jeśli w oknie trendu temperatura (po filtrze) wzrosła co najmniej o tę wartość,
      to przy T < set - deadband regulator NIE zwiększy mocy (bo i tak dogrzewa).

  - key: takeover_hold_fall_degC
    label: "Takeover: nie odejmuj mocy gdy T spada o ≥"
    type: number
    unit: "°C"
    min: 0
    max: 10
    step: 0.1
    default: 0.8
    group: takeover
    description: >
      Jeśli w oknie trendu temperatura (po filtrze) spadła co najmniej o tę wartość,
      to przy T > set + deadband regulator NIE zmniejszy mocy (bo i tak stygnie).

  - key: dropout_err_off_degC
    label: "Oddanie: |błąd| >= "
    type: number
    unit: "°C"
    min: 0
    max: 30
    step: 0.5
    default: 5.0
    group: takeover
    description: >
      Jeśli błąd przekroczy ten próg, moduł oddaje sterowanie i wraca do uczenia.

  - key: resume_takeover_enabled
    label: "Resume takeover po OFF→WORK"
    type: bool
    default: true
    group: takeover
    description: >
      Jeśli moduł był w takeover i tryb wyszedł z WORK, to po powrocie do WORK
      spróbuje wznowić takeover od poprzedniej komendy mocy (bez powrotu do baseline).

  - key: resume_takeover_max_gap_s
    label: "Resume: maks. przerwa OFF→WORK"
    type: number
    unit: "s"
    min: 0
    max: 7200
    step: 30
    default: 1200
    group: takeover
    description: >
      Jeśli przerwa między LEAVE WORK i ENTER WORK jest większa niż ten próg,
      resume jest pomijany.

  - key: resume_max_temp_delta_C
    label: "Resume: maks. ΔT"
    type: number
    unit: "°C"
    min: 0
    max: 50
    step: 0.5
    default: 5
    group: takeover
    description: >
      Jeśli temperatura (po filtrze lub surowa) po powrocie do WORK różni się od tej
      zapamiętanej przy wyjściu o więcej niż próg, resume jest pomijany.


  - key: boiler_temp_filter_tau_s
    label: "Filtr temp. kotła (tau)"
    type: number
    unit: "s"
    min: 0
    max: 300
    step: 1
    default: 15
    group: basic
    description: "Stała czasowa filtru dolnoprzepustowego na temperaturze kotła."

  - key: status_log_period_s
    label: "Log: okres statusu"
    type: number
    unit: "s"
    min: 1
    max: 3600
    step: 1
    default: 30
    group: basic
    description: "Co ile sekund emitować log stanu (status)."

  # --- learning (EMA) ---
  - key: temp_span_window_s
    label: "Stabilność: okno span(T)"
    type: number
    unit: "s"
    min: 60
    max: 7200
    step: 30
    default: 300
    group: learning
    description: >
      Okno czasowe do liczenia span(T)=max-min dla temperatury (po filtrze).

  - key: ema_tau_s
    label: "EMA: stała czasowa (tau)"
    type: number
    unit: "s"
    min: 60
    max: 7200
    step: 60
    default: 1200
    group: learning
    description: "Jak szybko baseline EMA dostosowuje się do warunków (większa = wolniej)."

  - key: learn_gate_err_degC
    label: "Uczenie: warunek |błąd| <= "
    type: number
    unit: "°C"
    min: 0
    max: 10
    step: 0.1
    default: 1.0
    group: learning
    description: "EMA uczy się tylko gdy błąd temperatury jest mały."

  - key: learn_max_span_degC
    label: "Uczenie: warunek span(T) <= "
    type: number
    unit: "°C"
    min: 0
    max: 10
    step: 0.05
    default: 0.5
    group: learning
    description: "EMA uczy się tylko gdy temperatura ma małe wahania w oknie (span)."

  - key: learn_min_time_s
    label: "Uczenie: minimalny czas"
    type: number
    unit: "s"
    min: 0
    max: 7200
    step: 30
    default: 600
    group: learning
    description: "Minimalny czas pracy w WORK wymagany przed przejęciem sterowania."

  - key: learn_min_samples
    label: "Uczenie: minimalna liczba próbek"
    type: number
    min: 0
    max: 5000
    step: 1
    default: 30
    group: learning
    description: "Minimalna liczba aktualizacji EMA wymaganych przed przejęciem sterowania."

  # --- state ---
  - key: state_dir
    label: "Katalog zapisu stanu"
    type: text
    default: "data"
    group: state
    description: "Katalog (względem modułu) używany tylko jako fallback, gdy brak data_root."

  - key: state_file
    label: "Plik stanu"
    type: text
    default: "power_work_predictive_state.yaml"
    group: state
    description: "Nazwa pliku, w którym zapisywany jest stan (EMA i liczniki)."

  - key: state_save_interval_s
    label: "Interwał zapisu stanu"
    type: number
    unit: "s"
    min: 1
    max: 3600
    step: 1
    default: 30
    group: state
    description: "Co ile sekund zapisywać stan na dysk."

  - key: state_max_age_s
    label: "Maks. wiek stanu"
    type: number
    unit: "s"
    min: 0
    max: 86400
    step: 60
    default: 900
    group: state
    description: "Jeśli plik stanu jest starszy niż ten próg, restore jest pomijany (0 = zawsze próbuj)."

  - key: state_max_temp_delta_C
    label: "Maks. różnica temp. przy restore"
    type: number
    unit: "°C"
    min: 0
    max: 50
    step: 0.5
    default: 5
    group: state
    description: "Jeśli aktualna temp. kotła różni się od zapisanej o więcej niż próg, restore jest pomijany."

