id: feeder
name: "Podajnik ślimakowy"
description: "Sterowanie cyklami ślimaka na podstawie mocy kotła (power%)."

groups:
  - id: basic
    label: "Podstawowe"

fields:
  - key: feed_on_base_s
    label: "Czas podawania (ON)"
    type: number
    unit: "s"
    min: 1
    max: 60
    step: 1
    default: 10
    group: basic

  - key: feed_off_base_s
    label: "Czas przerwy przy 100% mocy"
    type: number
    unit: "s"
    min: 10
    max: 300
    step: 1
    default: 64
    group: basic

  - key: min_power_to_feed
    label: "Minimalna moc do podawania"
    type: number
    unit: "%"
    min: 0
    max: 50
    step: 1
    default: 5
    group: basic

  - key: min_pause_s
    label: "Minimalna przerwa OFF"
    type: number
    unit: "s"
    min: 1
    max: 300
    step: 1
    default: 10
    group: basic

  - key: max_pause_s
    label: "Maksymalna przerwa OFF"
    type: number
    unit: "s"
    min: 30
    max: 3600
    step: 10
    default: 600
    group: basic
