id: overheat
name: "Przegrzanie"
description: >
  Moduł bezpieczeństwa:
  - przegrzanie kotła (boiler_temp): włącza pompy CO+CWU, wyłącza dmuchawę i ślimak, otwiera mieszacz.
  - przegrzanie podajnika (hopper_temp): włącza pompy CO+CWU, wyłącza dmuchawę, NIE otwiera mieszacza,
    uruchamia ślimak na czas (min) w celu wypchnięcia żaru.

groups:
  - id: basic
    label: "Podstawowe"
  - id: boiler
    label: "Przegrzanie kotła"
  - id: hopper
    label: "Przegrzanie podajnika"

fields:
  - key: enabled
    label: "Włącz moduł"
    type: bool
    default: true
    group: basic
    label_on: "WŁĄCZONE"
    label_off: "WYŁĄCZONE"
    description: "Globalne włączenie/wyłączenie ochrony."

  - key: boiler_trip_temp
    label: "Próg przegrzania kotła"
    type: number
    unit: "°C"
    min: 60
    max: 110
    step: 0.5
    default: 90
    group: boiler
    description: "Gdy boiler_temp >= próg, aktywuje zabezpieczenie kotła."

  - key: boiler_hysteresis
    label: "Histereza resetu kotła"
    type: number
    unit: "°C"
    min: 1
    max: 30
    step: 0.5
    default: 5
    group: boiler
    description: >
      Zabezpieczenie kotła wyłączy się dopiero gdy
      boiler_temp <= (boiler_trip_temp - boiler_hysteresis).

  - key: hopper_trip_temp
    label: "Próg przegrzania podajnika"
    type: number
    unit: "°C"
    min: 30
    max: 110
    step: 0.5
    default: 70
    group: hopper
    description: "Gdy hopper_temp >= próg, aktywuje zabezpieczenie podajnika."

  - key: hopper_hysteresis
    label: "Histereza resetu podajnika"
    type: number
    unit: "°C"
    min: 1
    max: 30
    step: 0.5
    default: 5
    group: hopper
    description: >
      Zabezpieczenie podajnika wyłączy się dopiero gdy
      hopper_temp <= (hopper_trip_temp - hopper_hysteresis).

  - key: hopper_purge_minutes
    label: "Czas wypchnięcia żaru (ślimak ON)"
    type: number
    unit: "min"
    min: 0
    max: 20
    step: 0.5
    default: 2
    group: hopper
    description: >
      Po wejściu w przegrzanie podajnika uruchamia ślimak na podany czas,
      aby wypchnąć żar i zmniejszyć ryzyko pożaru podajnika.
      0 = brak wypychania (samo odcięcie dmuchawy + pompy ON).
