id: mixer
name: "Zawór mieszający"
description: "Sterowanie zaworem mieszającym na podstawie temperatury za zaworem i kotła."

groups:
  - id: basic
    label: "Podstawowe"
  - id: ignition
    label: "Rozpalanie"

fields:
  - key: target_temp
    label: "Docelowa temperatura za zaworem"
    type: number
    unit: "°C"
    min: 20
    max: 70
    step: 1
    default: 40
    group: basic
    description: "Temperatura, do której dążymy za zaworem mieszającym (obieg grzejnikowy/podłoga)."

  - key: ok_band_degC
    label: "Martwa strefa przy zadanej"
    type: number
    unit: "°C"
    min: 0.5
    max: 10
    step: 0.5
    default: 2
    group: basic
    description: "Dopuszczalne odchylenie od zadanej, w którym zawór nie wykonuje ruchów, aby nie \"mielić\" zbyt często."

  - key: min_pulse_s
    label: "Minimalny czas ruchu zaworu"
    type: number
    unit: "s"
    min: 0.2
    max: 10
    step: 0.1
    default: 0.5
    group: basic
    description: "Najkrótszy impuls OTWÓRZ/ZAMKNIJ. Chroni przed bardzo krótkimi, nieefektywnymi ruchami."

  - key: max_pulse_s
    label: "Maksymalny czas ruchu zaworu"
    type: number
    unit: "s"
    min: 0.5
    max: 30
    step: 0.5
    default: 3
    group: basic
    description: "Najdłuższy pojedynczy impuls OTWÓRZ/ZAMKNIJ, aby nie przekręcić za mocno zaworu jednym ruchem."

  - key: adjust_interval_s
    label: "Minimalny odstęp między korektami"
    type: number
    unit: "s"
    min: 5
    max: 600
    step: 5
    default: 10
    group: basic
    description: "Jak często NAJSZYBCIEJ możemy wykonać kolejny ruch zaworu. Zwiększ przy dużej bezwładności instalacji."

  - key: ignition_open_boiler_temp
    label: "Temp. kotła do startu otwierania (IGNITION)"
    type: number
    unit: "°C"
    min: 30
    max: 90
    step: 1
    default: 55
    group: ignition
    description: "Poniżej tej temperatury kotła zawór nie będzie otwierany w trybie rozpalania, aby nie wychłodzić kotła zbyt wcześnie."

  - key: ignition_max_boiler_drop_degC
    label: "Maksymalny spadek kotła po otwarciu"
    type: number
    unit: "°C"
    min: 1
    max: 20
    step: 0.5
    default: 5
    group: ignition
    description: "Jeśli po ruchu OTWÓRZ w IGNITION kocioł spadnie o więcej niż tyle stopni, kolejne otwarcia będą tymczasowo blokowane."

  - key: ignition_recover_factor
    label: "Wymagane odbicie kotła po spadku"
    type: number
    unit: ""
    min: 0.1
    max: 1.0
    step: 0.1
    default: 0.5
    group: ignition
    description: >
      Jaka część spadku temperatury kotła musi zostać odrobiona, aby znieść blokadę kolejnych otwarć.
      Np. przy 0.5 i spadku 6°C czekamy, aż kocioł podniesie się o 3°C.
