id: power
name: "Regulator mocy kotła"
description: "Wyznaczanie mocy kotła (power %) z osobnym algorytmem rozpalania (IGNITION) – hybryda ΔT + dT/dt – oraz PID-em w trybie pracy (WORK)."

groups:
  - id: basic
    label: "Podstawowe"
  - id: ignition
    label: "Rozpalanie"
  - id: pid
    label: "PID"

fields:
  - key: boiler_set_temp
    label: "Zadana temperatura kotła"
    type: number
    unit: "°C"
    min: 40
    max: 90
    step: 1
    default: 65
    group: basic
    description: "Temperatura, do której regulator dąży sterując mocą kotła. Typowo równa zadanej temperaturze kotła w całym systemie."

  - key: min_power
    label: "Minimalna moc (globalnie)"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 0
    group: basic
    description: "Dolne ograniczenie wyliczonej mocy (dotyczy wszystkich trybów)."

  - key: max_power
    label: "Maksymalna moc (globalnie)"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 100
    group: basic
    description: "Górne ograniczenie wyliczonej mocy. Ustaw poniżej 100%, jeśli chcesz sztucznie „przydusić” kocioł."

  - key: mode
    label: "Tryb (gdy brak boiler_mode)"
    type: text
    options: ["auto", "ignition", "off"]
    default: "auto"
    group: basic
    description: >
      Lokalny tryb używany tylko awaryjnie, gdy SystemState.mode z jakiegoś powodu
      jest nieznany. "auto" – zwykła praca na PID (jak WORK), "ignition" – praca
      z algorytmem rozpalania, "off" – wyłączony (power = 0%).

  # --- IGNITION (ΔT) ---

  - key: ignition_high_power_percent
    label: "Moc w rozpalaniu przy dużym ΔT"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 100
    group: ignition
    description: >
      Moc w trybie IGNITION, gdy kocioł jest wyraźnie poniżej zadanej temperatury
      (różnica temperatur większa lub równa 'Pełna moc przy ΔT ≥'). Zwykle 80–100%.

  - key: ignition_min_power_percent
    label: "Minimalna moc w rozpalaniu"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 30
    group: ignition
    description: >
      Minimalna moc w trybie IGNITION. Zapewnia, że przy zbliżaniu się do zadanej
      temperatury kocioł nie zejdzie zbyt nisko z mocą i nie „zadusi” płomienia.

  - key: ignition_full_power_delta_degC
    label: "Pełna moc przy ΔT ≥"
    type: number
    unit: "°C"
    min: 1
    max: 40
    step: 1
    default: 15
    group: ignition
    description: >
      Jeśli kocioł jest poniżej zadanej co najmniej o tyle stopni, moc w IGNITION
      jest ustawiana na 'Moc w rozpalaniu przy dużym ΔT'. Im mniejsza wartość,
      tym szybciej moc zacznie spadać z pełnej wartości.

  - key: ignition_min_power_delta_degC
    label: "Minimalna moc przy ΔT ≤"
    type: number
    unit: "°C"
    min: 0
    max: 20
    step: 0.5
    default: 3
    group: ignition
    description: >
      Jeśli kocioł jest poniżej zadanej co najwyżej o tyle stopni, moc w IGNITION
      jest ustawiana na 'Minimalna moc w rozpalaniu'. W przedziale pomiędzy
      pełną a minimalną różnicą temperatur moc zmienia się płynnie (liniowo).

  # --- IGNITION – dT/dt (boost w górę) ---

  - key: ignition_target_rate_k_per_min
    label: "Docelowy przyrost temperatury"
    type: number
    unit: "°C/min"
    min: 0
    max: 5
    step: 0.1
    default: 0.8
    group: ignition
    description: >
      Docelowe tempo wzrostu temperatury kotła w trybie rozpalania (w stopniach
      Celsjusza na minutę). Jeśli kocioł nagrzewa się wolniej niż
      (target - pasmo), algorytm dodaje boost do mocy.

  - key: ignition_rate_band_k_per_min
    label: "Pas tolerancji tempa nagrzewania"
    type: number
    unit: "°C/min"
    min: 0
    max: 2
    step: 0.1
    default: 0.3
    group: ignition
    description: >
      Szerokość pasma tolerancji wokół docelowego tempa nagrzewania.
      Jeśli aktualny przyrost mieści się w zakresie
      (target - band, +∞), boost z dT/dt nie jest dodawany.
      Poniżej (target - band) moc jest podbijana.

  - key: ignition_rate_gain_percent_per_k_per_min
    label: "Wzmocnienie boosta z dT/dt"
    type: number
    unit: "pkt% / (°C/min)"
    min: 0
    max: 50
    step: 1
    default: 10
    group: ignition
    description: >
      Ile punktów procentowych mocy dodać za każdy 1°C/min brakujący do dolnej
      granicy pasma tempa nagrzewania. Np. 10 pkt%/(°C/min): jeśli brakuje
      0.5°C/min, boost wyniesie 5 punktów procentowych.

  - key: ignition_rate_max_boost_percent
    label: "Maksymalny boost z dT/dt"
    type: number
    unit: "pkt%"
    min: 0
    max: 100
    step: 1
    default: 30
    group: ignition
    description: >
      Maksymalna dodatkowa moc (w punktach procentowych) jaką algorytm dT/dt
      może dodać ponad moc wynikającą z różnicy temperatur (ΔT).

  # --- PID / WORK ---

  - key: kp
    label: "Kp (proporcjonalne)"
    type: number
    unit: ""
    min: 0
    max: 20
    step: 0.1
    default: 2.0
    group: pid
    description: "Wzmocnienie części proporcjonalnej PID. Im większe Kp, tym mocniej regulator reaguje na aktualny błąd temperatury kotła."

  - key: ki
    label: "Ki (całkujące)"
    type: number
    unit: "1/s"
    min: 0
    max: 1
    step: 0.001
    default: 0.01
    group: pid
    description: "Wzmocnienie części całkującej PID (1/s). Odpowiada za „dobijanie” do zadanej i likwidację uchybu ustalonego, ale zbyt duże może powodować przeregulowania."

  - key: kd
    label: "Kd (różniczkujące)"
    type: number
    unit: "s"
    min: 0
    max: 10
    step: 0.1
    default: 0.0
    group: pid
    description: "Wzmocnienie części różniczkującej PID. Reaguje na szybkość zmian temperatury (pochodna błędu) i pomaga wyhamować przed przeregulowaniem. Najczęściej zostawiane na 0 lub niskich wartościach."

  - key: integral_window_s
    label: "Okno czasowe całki"
    type: number
    unit: "s"
    min: 10
    max: 3600
    step: 10
    default: 300
    group: pid
    description: >
      Efektywne okno czasowe dla części całkującej. Im mniejsza wartość,
      tym szybciej regulator „zapomina” stare błędy i tym mniejszy windup
      przy długotrwałym dużym uchybie (np. podczas pracy na wysokiej mocy).

  - key: overtemp_start_degC
    label: "Próg przegrzania (powyżej zadanej)"
    type: number
    unit: "°C"
    min: 0
    max: 30
    step: 0.5
    default: 3
    group: pid
    description: >
      O ile stopni powyżej zadanej temperatury kotła zaczyna się dodatkowa
      korekta mocy przy przegrzaniu. Powyżej Tzadana + ten próg moc jest
      ekstra obniżana proporcjonalnie do wielkości przegrzania.

  - key: overtemp_kp
    label: "Siła korekty przy przegrzaniu"
    type: number
    unit: "pkt%/°C"
    min: 0
    max: 50
    step: 1
    default: 10
    group: pid
    description: >
      Ile punktów procentowych mocy odjąć za każdy dodatkowy stopień Celsjusza
      powyżej progu przegrzania. Np. 10 pkt%/°C: przy 2°C ponad próg przegrzania
      moc zostanie obniżona o 20 punktów procentowych względem wartości z PID.
