id: blower
name: "Dmuchawa"
description: "Sterowanie dmuchawą metodą duty (PRACA/POSTÓJ) na podstawie mocy kotła i temperatury spalin."

groups:
  - id: basic
    label: "Podstawowe"

fields:
  - key: base_fan_percent
    label: "Stałe obroty dmuchawy"
    type: number
    unit: "%"
    min: 5
    max: 100
    step: 1
    default: 45
    group: basic

  - key: min_power_to_blow
    label: "Minimalna moc kotła do włączenia dmuchawy"
    type: number
    unit: "%"
    min: 0
    max: 50
    step: 1
    default: 3
    group: basic

  - key: flue_control_enabled
    label: "Regulacja duty wg temp. spalin"
    type: bool
    default: true
    group: basic
    label_on: "WŁĄCZONA"
    label_off: "WYŁĄCZONA"

  - key: flue_opt_temp
    label: "Docelowa temp. spalin (praca)"
    type: number
    unit: "°C"
    min: 80
    max: 250
    step: 5
    default: 150
    group: basic

  - key: flue_kp
    label: "Czułość korekty duty z Tspalin"
    type: number
    unit: "%/°C"
    min: 0.0
    max: 2.0
    step: 0.05
    default: 0.10
    group: basic

  - key: flue_correction_max
    label: "Maksymalna korekta duty z Tspalin"
    type: number
    unit: "%"
    min: 0
    max: 50
    step: 1
    default: 20
    group: basic

  - key: cycle_time_s
    label: "Czas cyklu dmuchawy"
    type: number
    unit: "s"
    min: 5
    max: 120
    step: 5
    default: 30
    group: basic

  - key: flue_ignition_max_temp
    label: "Maks. temp. spalin w rozpalaniu"
    type: number
    unit: "°C"
    min: 80
    max: 300
    step: 5
    default: 200
    group: basic
