id: blower
name: "Dmuchawa"
description: "Sterowanie dmuchawą metodą duty (PRACA/POSTÓJ) na podstawie mocy kotła i temperatury spalin. Użytkownik ustawia stałe obroty, a sterownik wylicza czas pracy i postoju w cyklu."

groups:
  - id: basic
    label: "Podstawowe"

fields:
  - key: base_fan_percent
    label: "Stałe obroty dmuchawy"
    type: number
    unit: "%"
    min: 5
    max: 100
    step: 1
    default: 45
    group: basic
    description: "Stałe obroty dmuchawy, gdy jest w fazie PRACA. Sterownik tylko włącza/wyłącza dmuchawę wg wyliczonego duty."

  - key: min_power_to_blow
    label: "Minimalna moc kotła do włączenia dmuchawy"
    type: number
    unit: "%"
    min: 0
    max: 50
    step: 1
    default: 3
    group: basic
    description: "Poniżej tej mocy kotła dmuchawa pozostaje całkowicie wyłączona. Zapobiega niepotrzebnemu dmuchaniu przy bardzo małym zapotrzebowaniu na moc."

  - key: startup_enabled
    label: "Rozruch dmuchawy"
    type: bool
    default: false
    group: basic
    label_on: "WŁĄCZONY"
    label_off: "WYŁĄCZONY"
    description: "Jeśli włączone, po każdym uruchomieniu dmuchawy (0→>0) sterownik przez chwilę podaje 100%, a potem wraca do stałych obrotów."

  - key: startup_time_s
    label: "Czas rozruchu dmuchawy"
    type: number
    unit: "s"
    min: 0
    max: 30
    step: 0.5
    default: 0
    group: basic
    description: "Czas trwania rozruchu (100%) po starcie dmuchawy. Jeśli faza pracy z duty jest krótsza, rozruch trwa tylko tyle co faza pracy."

  - key: flue_control_enabled
    label: "Regulacja duty wg temp. spalin"
    type: bool
    default: true
    group: basic
    label_on: "WŁĄCZONA"
    label_off: "WYŁĄCZONA"
    description: "Czy korygować duty dmuchawy na podstawie temperatury spalin. Po wyłączeniu duty zależy wyłącznie od mocy kotła."

  - key: flue_opt_temp
    label: "Docelowa temp. spalin (praca)"
    type: number
    unit: "°C"
    min: 80
    max: 250
    step: 5
    default: 150
    group: basic
    description: "Docelowa temperatura spalin w trybie pracy (WORK). Dmuchawa będzie delikatnie zwiększać lub zmniejszać duty, aby zbliżać się do tej wartości."

  - key: flue_kp
    label: "Czułość korekty duty z Tspalin"
    type: number
    unit: "%/°C"
    min: 0.0
    max: 2.0
    step: 0.05
    default: 0.10
    group: basic
    description: "Określa, jak mocno błąd temperatury spalin (różnica względem zadanego punktu) wpływa na zmianę duty. Im większa wartość, tym szybciej dmuchawa reaguje na odchyłki Tspalin."

  - key: flue_correction_max
    label: "Maksymalna korekta duty z Tspalin"
    type: number
    unit: "%"
    min: 0
    max: 50
    step: 1
    default: 20
    group: basic
    description: "Maksymalny zakres korekty duty wynikającej z temperatury spalin względem wartości bazowej z mocy kotła (w górę lub w dół). Ogranicza zbyt agresywne zmiany pracy dmuchawy."

  - key: cycle_time_s
    label: "Czas cyklu dmuchawy"
    type: number
    unit: "s"
    min: 5
    max: 120
    step: 5
    default: 30
    group: basic
    description: "Długość pełnego cyklu PRACA+POSTÓJ. Np. przy 30 s i 50% mocy dmuchawa pracuje ok. 15 s i 15 s stoi."

  - key: flue_ignition_max_temp
    label: "Maks. temp. spalin w rozpalaniu"
    type: number
    unit: "°C"
    min: 80
    max: 300
    step: 5
    default: 200
    group: basic
    description: "Maksymalna dopuszczalna temperatura spalin w trybie rozpalania (IGNITION). Po jej przekroczeniu sterownik zmniejsza duty, aby nie przegrzewać kotła na starcie."

