id: blower
name: "Dmuchawa"
description: "Sterowanie dmuchawą na podstawie mocy kotła i temperatury spalin."

groups:
  - id: basic
    label: "Podstawowe"

fields:
  - key: base_fan_percent
    label: "Nominalna moc dmuchawy (PWN)"
    type: number
    unit: "%"
    min: 5
    max: 100
    step: 1
    default: 45
    group: basic

  - key: min_fan_percent
    label: "Minimalna moc dmuchawy"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 0
    group: basic

  - key: max_fan_percent
    label: "Maksymalna moc dmuchawy"
    type: number
    unit: "%"
    min: 10
    max: 100
    step: 1
    default: 100
    group: basic

  - key: min_power_to_blow
    label: "Minimalna moc kotła do włączenia dmuchawy"
    type: number
    unit: "%"
    min: 0
    max: 50
    step: 1
    default: 3
    group: basic

  - key: ignition_fan_boost_percent
    label: "Boost dmuchawy w rozpalaniu"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 20
    group: basic

  - key: ignition_min_fan_percent
    label: "Minimalna moc dmuchawy w rozpalaniu"
    type: number
    unit: "%"
    min: 5
    max: 100
    step: 1
    default: 25
    group: basic

  - key: flue_control_enabled
    label: "Regulacja wg temp. spalin"
    type: bool
    default: true
    group: basic
    label_on: "WŁĄCZONA"
    label_off: "WYŁĄCZONA"

  - key: flue_opt_temp
    label: "Docelowa temp. spalin"
    type: number
    unit: "°C"
    min: 80
    max: 250
    step: 5
    default: 150
    group: basic

  - key: flue_kp
    label: "Czułość korekty z Tspalin"
    type: number
    unit: "%/°C"
    min: 0.0
    max: 2.0
    step: 0.05
    default: 0.10
    group: basic

  - key: flue_correction_max
    label: "Maksymalna korekta z Tspalin"
    type: number
    unit: "%"
    min: 0
    max: 50
    step: 1
    default: 20
    group: basic
