# schema.yaml
id: power_work_fuzzy
name: "Moc kotła – PRACA (Fuzzy)"
description: "Wyznaczanie mocy kotła (power %) w trybie WORK na podstawie Mamdani Fuzzy Logic: temp. kotła + temp. spalin."

groups:
  - id: basic
    label: "Podstawowe"
  - id: filters
    label: "Filtry"
  - id: fuzzy
    label: "Fuzzy"
  - id: state
    label: "Stan (restart)"

fields:
  - key: enabled
    label: "Regulator aktywny"
    type: bool
    default: true
    label_on: "WŁĄCZONE"
    label_off: "WYŁĄCZONE"
    group: basic
    description: >
      Gdy wyłączone, moduł power_work_fuzzy nie nadpisuje outputs.power_percent.
      Tylko śledzi aktualną moc, żeby po włączeniu nie było skoku.

  - key: boiler_set_temp
    label: "Zadana temperatura kotła"
    type: number
    unit: "°C"
    min: 40
    max: 90
    step: 0.5
    default: 56.0
    group: basic

  - key: min_power
    label: "Minimalna moc"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 15
    group: basic

  - key: max_power
    label: "Maksymalna moc"
    type: number
    unit: "%"
    min: 0
    max: 100
    step: 1
    default: 100
    group: basic

  - key: max_slew_rate_percent_per_min
    label: "Maksymalna zmiana mocy na minutę"
    type: number
    unit: "pkt%/min"
    min: 0
    max: 100
    step: 0.5
    default: 10
    group: basic

  - key: boiler_tau_s
    label: "Stała filtru temp. kotła"
    type: number
    unit: "s"
    min: 10
    max: 1200
    step: 10
    default: 180
    group: filters

  - key: flue_tau_s
    label: "Stała filtru temp. spalin"
    type: number
    unit: "s"
    min: 5
    max: 600
    step: 5
    default: 60
    group: filters

  - key: delta_scale
    label: "Skala ΔP (agresywność)"
    type: number
    unit: ""
    min: 0
    max: 3
    step: 0.05
    default: 0.8
    group: fuzzy
    description: "Mnożnik na wynik fuzzy (ΔP). Najprostszy parametr do strojenia."

  - key: delta_universe_step
    label: "Krok defuzyfikacji (dokładność)"
    type: number
    unit: ""
    min: 0.01
    max: 0.5
    step: 0.01
    default: 0.05
    group: fuzzy
    description: "Im mniejszy krok, tym dokładniejszy centroid (kosztem CPU)."

  - key: flue_min_C
    label: "Spaliny: niski poziom (min)"
    type: number
    unit: "°C"
    min: 0
    max: 300
    step: 0.5
    default: 58
    group: fuzzy

  - key: flue_mid_C
    label: "Spaliny: typowy poziom (środek)"
    type: number
    unit: "°C"
    min: 0
    max: 300
    step: 0.5
    default: 66
    group: fuzzy

  - key: flue_max_C
    label: "Spaliny: wysoki poziom (max)"
    type: number
    unit: "°C"
    min: 0
    max: 300
    step: 0.5
    default: 76
    group: fuzzy

  - key: flue_overlap_ratio
    label: "Spaliny: overlap zbiorów"
    type: number
    unit: ""
    min: 0.05
    max: 0.45
    step: 0.01
    default: 0.20
    group: fuzzy

  - key: flue_vhigh_margin_C
    label: "Spaliny: margines VHIGH ponad max"
    type: number
    unit: "°C"
    min: 0
    max: 100
    step: 0.5
    default: 8
    group: fuzzy

  - key: state_dir
    label: "Katalog zapisu stanu"
    type: text
    default: "data"
    group: state

  - key: state_file
    label: "Plik stanu"
    type: text
    default: "power_work_fuzzy_state.yaml"
    group: state

  - key: state_save_interval_s
    label: "Interwał zapisu stanu"
    type: number
    unit: "s"
    min: 1
    max: 3600
    step: 1
    default: 30
    group: state

  - key: state_max_age_s
    label: "Maksymalny wiek stanu"
    type: number
    unit: "s"
    min: 0
    max: 86400
    step: 60
    default: 900
    group: state

  - key: state_max_boiler_temp_delta_C
    label: "Maks. różnica temp. kotła przy restore"
    type: number
    unit: "°C"
    min: 0
    max: 50
    step: 0.5
    default: 5
    group: state

  - key: state_max_flue_temp_delta_C
    label: "Maks. różnica temp. spalin przy restore"
    type: number
    unit: "°C"
    min: 0
    max: 200
    step: 1
    default: 30
    group: state

